CREATE DATABSE onlinedb;
CREATE table product(
id INTEGER primary key GENERATED BY DEFAULT AS IDENTITY,
name varchar(255),
ptype varchar(255),
price numeric NOT NULL,
description text,
createdat timestamp NOT NULL,
image varchar(255)

);

CREATE TABLE users(
id INTEGER primary key GENERATED BY DEFAULT AS IDENTITY,
firstname varchar(255),
lastname varchar(255),
password varchar(255),


);
CREATE TABLE balance(
id INTEGER,
balance numeric default value 0
);
